name: Daily Script

on:
  schedule:
    - cron: "0 4 * * *"  # runs every day at 8am UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          SPYDUS_PASSWORD: ${{ secrets.SPYDUS_PASSWORD }}
          SPYDUS_USERNAME: ${{ secrets.SPYDUS_USERNAME }}
        run: python main.py

      - name: Upload screenshot on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: debug.png
